
name: 'shopify_source'
version: '1.0.0'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  shopify_source:
    customer_source: "{{ source('shopify','customer') }}"
    order_line_refund_source: "{{ source('shopify','order_line_refund') }}"
    order_line_source: "{{ source('shopify','order_line') }}"
    order_source: "{{ source('shopify','order') }}"
    product_source: "{{ source('shopify','product') }}"

models:
  shopify_source:
    materialized: view